name: schulcloud
description: A Flutter–based mobile app for the HPI Schul–Cloud.
# Version Code: MM mm pp P nnn (max: 2 100 000 000)
# MM: Major version (0 – 20)
# mm: Minor version (0 – 99)
# pp: Patch version (0 – 99)
# P: Preview (2: canary, 4: alpha, 5: beta, 8: RC)
# nnn: Preview version (0 – 999)
#
# e.g. 1.23.4-beta.12 ≙ 01 23 04 5 012
version: 0.3.5
homepage: https://github.com/hpi-schul-cloud/schulcloud-flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.22.0 <1.23.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  banners: ^0.2.0
  black_hole_flutter: ^0.2.13
  collection: ^1.14.13
  cupertino_icons: ^0.1.2
  datetime_picker_formfield: ^1.0.0
  device_info: ^0.4.2+4
  file_picker: ^1.13.2
  flare_flutter: ^2.0.6
  flutter_absolute_path: ^1.0.6
  flutter_deep_linking: ^0.1.2
  flutter_downloader: ^1.4.4
  flutter_html: ^1.0.2
  flutter_inappwebview: ^4.0.0+4
  flutter_native_timezone: ^1.0.4
  flutter_svg: ^0.17.4
  flutter_villains: ^1.2.1
  font_awesome_flutter: ^8.8.1
  get_it: ^4.0.4
  grec_minimal: ^0.0.4
  hive: ^1.4.2
  hive_cache:
    git:
      url: git://github.com/marcelgarus/hive_cache
      ref: ad7ecd2
  hive_flutter: ^0.3.1
  html: ^0.14.0+3
  http: ^0.12.2
  intl: ^0.16.1
  logger: ^0.7.0+1
  logger_flutter: ^0.7.1
  meta: ^1.1.8
  mime: ^0.9.6+3
  navigation_patterns:
    git:
      url: https://github.com/JonasWanke/navigation_patterns.git
      ref: b1841ad
  package_info: ">=0.4.1 <2.0.0"
  path_provider: ^1.6.11
  permission_handler: ^3.3.0
  rxdart: ^0.24.1
  sentry: ^3.0.1
  share:
    git:
      url: https://github.com/d-silveira/flutter-share.git
      ref: 1f8b139
  swipeable_page_route: ^0.1.3
  streaming_shared_preferences: ^1.0.1
  system_info: ^0.1.3
  time_machine: ^0.9.13
  transparent_image: ^1.0.0
  uni_links: ^0.4.0
  url_launcher: ^5.5.0
dependency_overrides:
  dartx: ^0.5.0
  flutter_svg: ^0.18.0

dev_dependencies:
  build_resolvers: ^1.3.10
  build_runner: ^1.10.1
  extra_pedantic: ^1.2.0
  flutter_driver:
    sdk: flutter
  hive_generator: ^0.7.1
  intl_utils: ^1.6.3
  mockito: ^4.1.1
  # screenshots: ^2.1.1
  # We need to use a version compatible with test_api 0.2.11 required by flutter_driver.
  test: ^1.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/empty_states/default.svg
    - assets/empty_states/broken_pen.svg
    - assets/empty_states/files.flr
    - assets/icon_signOut.svg
    - assets/file_thumbnails/
    - assets/sloth_error.svg
    - assets/theme/sc/logo/logo_with_text.svg
    - assets/theme/brb/logo/logo_with_text.svg
    - assets/theme/n21/logo/logo_with_text.svg
    - assets/theme/n21/logo/dark/logo_with_text.svg
    - assets/theme/open/logo/logo_with_text.svg
    - assets/theme/open/logo/dark/logo_with_text.svg
    - assets/theme/thr/logo/logo_with_text.svg
    - assets/theme/thr/logo/dark/logo_with_text.svg
    - packages/time_machine/data/cultures/cultures.bin
    - packages/time_machine/data/tzdb/tzdb.bin

  fonts:
    - family: PT Sans
      fonts:
        - asset: assets/fonts/pt_sans_regular.ttf
          weight: 300
        - asset: assets/fonts/pt_sans_bold.ttf
          weight: 700
    - family: PT Sans Narrow
      fonts:
        - asset: assets/fonts/pt_sans_narrow_regular.ttf
          weight: 300
        - asset: assets/fonts/pt_sans_narrow_bold.ttf
          weight: 700

flutter_intl:
  enabled: true
