name: schulcloud
description: A Flutter–based mobile app for the HPI Schul–Cloud.
version: 1.0.0+1
homepage: https://github.com/schul-cloud/schulcloud-flutter

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  analyzer: ^0.39.4
  cupertino_icons: ^0.1.2
  datetime_picker_formfield: ^1.0.0
  flare_flutter: ^1.5.8
  flutter_cached: ^3.0.1
  # The current version of flutter_downloader, 1.2.1, causes the build to fail. Until this is fixed, we rely on an older version.
  flutter_downloader: 1.1.9
  flutter_html: ^0.10.4
  flutter_native_timezone: ^1.0.4
  flutter_svg: ^0.14.2
  flutter_villains: ^1.2.0
  get_it: ^4.0.0-beta.3
  grec_minimal: ^0.0.3
  hive: ^1.2.0
  hive_flutter: ^0.3.0+1
  html: ^0.14.0+3
  http: ^0.12.0
  intl: ^0.16.0
  list_diff: ^1.1.3
  logger: ^0.7.0+1
  logger_flutter: ^0.7.1
  meta: ^1.1.8
  package_info: ^0.4.0+3
  pedantic: ^1.8.0+1
  path_provider: ^1.1.0
  permission_handler: ^3.3.0
  provider: ^4.0.0
  rxdart: ^0.22.3
  sprintf: ^4.0.2
  streaming_shared_preferences: ^1.0.1
  time_machine: ^0.9.12
  transparent_image: ^1.0.0
  url_launcher: ^5.1.2
  # Using a fork until the main plugin supports transparent backgrounds:
  # https://github.com/flutter/flutter/issues/29300
  # webview_flutter: ^0.3.10+4
  webview_flutter:
    git:
      url: git://github.com/jaumard/plugins
      ref: feature/webview_transparency
      path: packages/webview_flutter

dev_dependencies:
  build_resolvers: ^1.1.1
  build_runner: ^1.0.0
  hive_generator: ^0.7.0
  intl_utils: ^1.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/empty_states/default.svg
    - assets/empty_states/broken_pen.svg
    - assets/empty_states/files.flr
    - assets/icon_signOut.svg
    - assets/file_thumbnails/
    - assets/theme/sc/logo/logo_with_text.svg
    - assets/theme/brb/logo/logo_with_text.svg
    - assets/theme/n21/logo/logo_with_text.svg
    - assets/theme/n21/logo/dark/logo_with_text.svg
    - assets/theme/open/logo/logo_with_text.svg
    - assets/theme/open/logo/dark/logo_with_text.svg
    - assets/theme/thr/logo/logo_with_text.svg
    - assets/theme/thr/logo/dark/logo_with_text.svg
    - packages/time_machine/data/cultures/cultures.bin
    - packages/time_machine/data/tzdb/tzdb.bin

  fonts:
    - family: PT Sans
      fonts:
        - asset: assets/fonts/pt_sans_regular.ttf
          weight: 300
        - asset: assets/fonts/pt_sans_bold.ttf
          weight: 700
    - family: PT Sans Narrow
      fonts:
        - asset: assets/fonts/pt_sans_narrow_regular.ttf
          weight: 300
        - asset: assets/fonts/pt_sans_narrow_bold.ttf
          weight: 700

flutter_intl:
  enabled: true
