name: Unicorn

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  unicorn:
    name: ðŸ¦„ Unicorn
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JonasWanke/unicorn@9b4b462
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
