name: entity_generator
version: 1.0.0

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  repositories:
    path: ../repositories

  build: '>=0.12.0 <2.0.0'
  source_gen: ^0.9.0
  
dev_dependencies:
  build_test: ^0.10.0
  build_runner: '>=0.9.0 <0.11.0'
  test: ^1.0.0
